version: 2
updates:
  - package-ecosystem: "nuget"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "DevRocks.Ocelot.Grpc"
      - dependency-name: "DevRocks.Ocelot.Swagger"
  
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"